branch-defaults:
  # Elastic Beanstalk 환경 추가하는 방법
  # <BRANCH-NAME>:
  #   environmant: <ENV-NAME>
  gyu:
    environment: timbre-api-env
  master:
    environment: timbre-api-env
    group_suffix: null
global:
  application_name: timbre-api
  branch: null
  default_ec2_keyname: timbre-keypair
  default_platform: 64bit Amazon Linux 2017.09 v4.4.4 running Node.js
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
