# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
      - image: circleci/mysql:5.7
      - image: redis:latest

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # update packages
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
  deploy:
    docker:
      - image: circleci/node:latest
      - image: circleci/mysql:5.7
      - image: redis:latest
      
    steps:
      - checkout
      # install python and pip
      - run: sudo apt-get update
      - run: sudo apt-get install python3 python3-dev
      - run: curl -O https://bootstrap.pypa.io/get-pip.py
      - run: python3 get-pip.py --user
      # installing aws eb cli
      - run: ~/.local/bin/pip install awsebcli --upgrade --user
      - run: bash ./setup-eb.sh
      - run: ~/.local/bin/eb list
      - run: ~/.local/bin/eb deploy


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
