# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/mysql:5.7

    steps:
      - checkout
      # update npm
      - run: sudo npm install -g npm@latest

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # update packages
      - run: sudo npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
  test:
    docker:
      - image: circleci/node:latest
      - image: circleci/mysql:5.7
    steps:
      - checkout
      - run:
        name: Test
        command: npm test

  deploy:
    docker:
      - image: circleci/node:latest
      - image: circleci/mysql:5.7
    steps:
      - checkout
      # install python and pip
      - run: sudo apt-get update
      - run: sudo apt-get install python3
      - run: sudo apt-get install python3-dev
      - run: curl -O https://bootstrap.pypa.io/get-pip.py
      - run: python3 get-pip.py --user
      # DEBUG INFORMATION
      - run: ls -al ~/.local/bin
      # installing aws eb cli
      - run: ~/.local/bin/pip install awsebcli --upgrade --user
      # deploy
      - run: ~/.local/bin/eb deploy --profile default


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
